---
title: "Classification Models"
author: "Emmett Powers"
date: "12/7/2019"
output:
  pdf_document: default
  html_document: default
---

Preparing Data:
```{r}
library(rlist)
library(dplyr)
library(tidyverse)
library(jsonlite)

business <- stream_in(file("business.json"))
clean.business <- business
clean.business$Restaurant <- 0 
new.business <- mutate(clean.business, Restaurant=grepl("Restaurants", clean.business$categories))
clean.yelp <- filter(new.business, Restaurant == "TRUE")
attribute <- clean.yelp$attributes
restaurant_data <- clean.yelp
restaurant_data$attributes <- NULL
restaurant_data <- cbind(restaurant_data, attribute)
rdata <- subset(restaurant_data, select=voi)
rdata.clean <- rdata[complete.cases(rdata),]
```

Classification tree: 
```{r}
library(rpart)
library(rpart.plot)
model2 <- rpart(RestaurantsPriceRange2 ~ stars + review_count + latitude + longitude, data = rdata.clean,
  control = rpart.control(minsplit = 2))
plot1<-prp(model2)
```


Random Forest: 
```{r}
boot_ind <- sample(1:nrow(rdata.clean), 
                   replace = TRUE)
food_boot <- rdata.clean[boot_ind, ]
m <- sqrt(ncol(food_boot))
names(food_boot)
rforest_ind <- sample(1:ncol(food_boot),
                      size = m, replace = FALSE)
rforest_ind
food_rforest <- food_boot[, c(, rforest_ind),  ]
tree(RestaurantsPriceRange2 ~., data = food_rforest)
```

Making smol datasts: 
```{r}
s.size2 <- floor(0.05 * nrow(train))
set.seed(11)
tinysubset <- sample(seq_len(nrow(train)), size = s.size2)
smol.data <- rdata.clean[tinysubset,]

s.size3 <- floor(0.0005 * nrow(train))
set.seed(12)
tinysubset2 <- sample(seq_len(nrow(train)), size = s.size3)
smoler.data <- rdata.clean[tinysubset2,]

```

Random Forest 2: 
```{r}
boot_ind2 <- sample(1:nrow(smol.data), 
                   replace = TRUE)
food_boot2 <- rdata.clean[boot_ind2, ]
m2 <- sqrt(ncol(food_boot2))
names(food_boot2)
rforest_ind2 <- sample(1:ncol(food_boot2),
                      size = m, replace = FALSE)
rforest_ind2
food_rforest2 <- food_boot2[ , c(rforest_ind2),  ]
```

```{r}
library(rpart)
library(rpart.plot)
m3 <- rpart(RestaurantsPriceRange2 ~ stars + review_count + latitude + longitude, data = food_rforest2)
```

Subsetting train and test data: 
```{r}
library(tidyverse)
class <- ordered(rdata.clean$RestaurantsPriceRange2, levels= c("1", "2", "3", "4")) 
rdata.clean$class <- class
s.size <- floor(0.75 * nrow(rdata.clean))
set.seed(10)
train.data <- sample(seq_len(nrow(rdata.clean)), size = s.size)
train <- rdata.clean[train.data, ]
test <- rdata.clean[-train.data, ]

```

OLR 
```{r}
library(MASS)
m2 <- polr(class ~ stars + review_count + latitude + longitude,  data = train,  Hess = TRUE) #this makes r crash
m2
predicted.price <- predict(m2, newdata = test)
predicted.price

# misclassification rate: 

plot(yp,yt)

yp <- predicted.price
yt <- test$RestaurantsPriceRange2

mcr.table <- table(yp,yt)
1-sum(diag(mcr.table))/sum(mcr.table)
```

LM 
```{r}
lm.train <- na.omit(train)
lin.mod <- lm(RestaurantsPriceRange2 ~ stars + review_count + latitude + longitude,  data = lm.train)
lin.mod.test <- predict(lin.mod, newdata = test)
```
